/**
 * Certification Catalog — Single source of truth for all known certifications.
 * Both the single generator and bulk generator import from here.
 */

import type { CertInfo } from './generator-utils';

export const KNOWN_CERTS: Record<string, CertInfo> = {
    // ── ISC2 ──
    cissp: {
        slug: 'cissp',
        name: 'CISSP (Certified Information Systems Security Professional)',
        issuer: 'ISC2',
        domains: [
            { id: 'sam', name: 'Security and Risk Management', weight: '15%', topics: ['CIA triad', 'security governance', 'compliance', 'legal & regulatory', 'professional ethics', 'BCP', 'risk management', 'threat modeling', 'supply chain risk', 'security awareness'] },
            { id: 'as', name: 'Asset Security', weight: '10%', topics: ['data classification', 'data ownership', 'privacy protection', 'asset retention', 'data security controls', 'data handling requirements'] },
            { id: 'se', name: 'Security Architecture and Engineering', weight: '13%', topics: ['security models', 'security evaluation', 'secure design patterns', 'cryptography', 'site & facility security', 'physical security'] },
            { id: 'cns', name: 'Communication and Network Security', weight: '13%', topics: ['network models', 'IP networking', 'wireless security', 'network protocols', 'network attacks', 'network security devices'] },
            { id: 'iam', name: 'Identity and Access Management', weight: '13%', topics: ['physical & logical access', 'identification & authentication', 'identity as a service', 'authorization mechanisms', 'access control attacks', 'identity lifecycle'] },
            { id: 'sa', name: 'Security Assessment and Testing', weight: '12%', topics: ['vulnerability assessment', 'penetration testing', 'log reviews', 'SOC reports', 'security audits', 'KPIs & metrics'] },
            { id: 'so', name: 'Security Operations', weight: '13%', topics: ['investigation types', 'evidence handling', 'incident management', 'disaster recovery', 'business continuity', 'change management', 'physical security operations'] },
            { id: 'ssd', name: 'Software Development Security', weight: '11%', topics: ['SDLC', 'development methodologies', 'maturity models', 'secure coding', 'code review', 'software testing', 'API security', 'DevSecOps'] },
        ],
    },
    cc: {
        slug: 'cc',
        name: 'CC (Certified in Cybersecurity)',
        issuer: 'ISC2',
        domains: [
            { id: 'sp', name: 'Security Principles', weight: '26%', topics: ['CIA triad', 'authentication', 'non-repudiation', 'privacy', 'governance', 'risk management', 'compliance'] },
            { id: 'bc', name: 'Business Continuity, Disaster Recovery & Incident Response', weight: '10%', topics: ['BCP', 'DRP', 'incident response', 'backup strategies'] },
            { id: 'ac', name: 'Access Controls Concepts', weight: '22%', topics: ['access control models', 'RBAC', 'MAC', 'DAC', 'least privilege', 'segregation of duties'] },
            { id: 'ns', name: 'Network Security', weight: '24%', topics: ['OSI model', 'TCP/IP', 'ports & protocols', 'firewalls', 'IDS/IPS', 'VPN', 'wireless security'] },
            { id: 'so', name: 'Security Operations', weight: '18%', topics: ['data handling', 'logging & monitoring', 'encryption', 'hardening', 'security policies', 'awareness training'] },
        ],
    },
    sscp: {
        slug: 'sscp',
        name: 'SSCP (Systems Security Certified Practitioner)',
        issuer: 'ISC2',
        domains: [
            { id: 'sao', name: 'Security Operations and Administration', weight: '16%', topics: ['security concepts', 'asset management', 'change management', 'security awareness'] },
            { id: 'ac', name: 'Access Controls', weight: '15%', topics: ['access control models', 'authentication methods', 'internetwork trust', 'identity management'] },
            { id: 'ria', name: 'Risk Identification, Monitoring, and Analysis', weight: '15%', topics: ['risk management', 'vulnerability assessment', 'security monitoring', 'risk frameworks'] },
            { id: 'ir', name: 'Incident Response and Recovery', weight: '14%', topics: ['incident handling', 'forensic investigation', 'BCP', 'DRP'] },
            { id: 'cry', name: 'Cryptography', weight: '9%', topics: ['symmetric/asymmetric encryption', 'hashing', 'PKI', 'digital signatures', 'key management'] },
            { id: 'ns', name: 'Network and Communications Security', weight: '16%', topics: ['network fundamentals', 'wireless security', 'network attacks', 'network access control'] },
            { id: 'sse', name: 'Systems and Application Security', weight: '15%', topics: ['malware', 'endpoint protection', 'cloud security', 'secure SDLC', 'virtual environments'] },
        ],
    },
    ccsp: {
        slug: 'ccsp',
        name: 'CCSP (Certified Cloud Security Professional)',
        issuer: 'ISC2',
        domains: [
            { id: 'cc', name: 'Cloud Concepts, Architecture and Design', weight: '17%', topics: ['cloud computing concepts', 'cloud reference architecture', 'cloud security concepts', 'design principles'] },
            { id: 'cds', name: 'Cloud Data Security', weight: '20%', topics: ['cloud data lifecycle', 'data classification', 'data privacy', 'data rights management', 'data retention'] },
            { id: 'cps', name: 'Cloud Platform & Infrastructure Security', weight: '17%', topics: ['cloud infrastructure', 'risk assessment', 'virtualization security', 'countermeasures', 'BCP/DRP'] },
            { id: 'cas', name: 'Cloud Application Security', weight: '17%', topics: ['application security threats', 'SDLC', 'application assurance', 'identity federation'] },
            { id: 'co', name: 'Cloud Security Operations', weight: '16%', topics: ['physical & logical infrastructure', 'operational controls', 'digital forensics', 'communication'] },
            { id: 'lr', name: 'Legal, Risk and Compliance', weight: '13%', topics: ['legal requirements', 'privacy issues', 'audit processes', 'risk management', 'outsourcing'] },
        ],
    },
    cgrc: {
        slug: 'cgrc',
        name: 'CGRC (Certified in Governance, Risk and Compliance)',
        issuer: 'ISC2',
        domains: [
            { id: 'is', name: 'Information Security Risk Management Program', weight: '16%', topics: ['risk frameworks', 'risk assessment methodology', 'system categorization'] },
            { id: 'sc', name: 'Scope of the Information System', weight: '11%', topics: ['system boundaries', 'information types', 'system authorization'] },
            { id: 'sg', name: 'Selection and Approval of Security and Privacy Controls', weight: '15%', topics: ['control selection', 'tailoring', 'overlay application'] },
            { id: 'si', name: 'Implementation of Security and Privacy Controls', weight: '16%', topics: ['control implementation', 'documentation', 'configuration management'] },
            { id: 'as', name: 'Assessment/Audit of Security and Privacy Controls', weight: '15%', topics: ['assessment planning', 'assessment execution', 'evidence collection'] },
            { id: 'ar', name: 'Authorization/Approval of Information System', weight: '10%', topics: ['authorization decision', 'risk acceptance', 'plan of action'] },
            { id: 'cm', name: 'Continuous Monitoring', weight: '17%', topics: ['ongoing assessment', 'security status reporting', 'configuration management'] },
        ],
    },
    hcispp: {
        slug: 'hcispp',
        name: 'HCISPP (HealthCare Information Security and Privacy Practitioner)',
        issuer: 'ISC2',
        domains: [
            { id: 'hc', name: 'Healthcare Industry', weight: '12%', topics: ['healthcare systems', 'health data management', 'third-party relationships'] },
            { id: 'ir', name: 'Information Governance in Healthcare', weight: '12%', topics: ['governance frameworks', 'information lifecycle', 'data stewardship'] },
            { id: 'tf', name: 'Information Technologies in Healthcare', weight: '12%', topics: ['EHR systems', 'health IT standards', 'interoperability'] },
            { id: 'rr', name: 'Regulatory and Standards Environment', weight: '15%', topics: ['HIPAA', 'HITECH', 'state regulations', 'international standards'] },
            { id: 'pp', name: 'Privacy and Security in Healthcare', weight: '22%', topics: ['PHI protection', 'access controls', 'audit controls', 'encryption'] },
            { id: 'rm', name: 'Risk Management and Risk Assessment', weight: '17%', topics: ['risk analysis', 'risk mitigation', 'vulnerability management'] },
            { id: 'tpc', name: 'Third-Party Management', weight: '10%', topics: ['BAAs', 'vendor risk assessment', 'cloud providers'] },
        ],
    },
    // ── CompTIA ──
    'security+': {
        slug: 'security-plus',
        name: 'CompTIA Security+ (SY0-701)',
        issuer: 'CompTIA',
        domains: [
            { id: 'gc', name: 'General Security Concepts', weight: '12%', topics: ['security controls', 'CIA triad', 'authentication', 'authorization', 'zero trust', 'gap analysis'] },
            { id: 'ta', name: 'Threats, Vulnerabilities, and Mitigations', weight: '22%', topics: ['threat actors', 'attack surfaces', 'social engineering', 'malware', 'cryptographic attacks', 'indicators of compromise'] },
            { id: 'sa', name: 'Security Architecture', weight: '18%', topics: ['architecture models', 'infrastructure concepts', 'secure communication', 'cloud security', 'virtualization', 'IoT security', 'ICS/SCADA'] },
            { id: 'so', name: 'Security Operations', weight: '28%', topics: ['monitoring', 'vulnerability management', 'incident response', 'digital forensics', 'automation', 'logging', 'alerting'] },
            { id: 'pm', name: 'Security Program Management and Oversight', weight: '20%', topics: ['governance', 'risk management', 'compliance', 'security policies', 'awareness programs', 'audits'] },
        ],
    },
    'network+': {
        slug: 'network-plus',
        name: 'CompTIA Network+ (N10-009)',
        issuer: 'CompTIA',
        domains: [
            { id: 'nf', name: 'Networking Fundamentals', weight: '24%', topics: ['OSI model', 'TCP/IP', 'IP addressing', 'subnetting', 'ports & protocols', 'network topologies'] },
            { id: 'ni', name: 'Network Implementation', weight: '19%', topics: ['routing', 'switching', 'wireless', 'WAN technologies', 'network services'] },
            { id: 'no', name: 'Network Operations', weight: '16%', topics: ['monitoring', 'documentation', 'business continuity', 'disaster recovery'] },
            { id: 'ns', name: 'Network Security', weight: '19%', topics: ['security concepts', 'network attacks', 'hardening', 'remote access'] },
            { id: 'nt', name: 'Network Troubleshooting', weight: '22%', topics: ['troubleshooting methodology', 'cable connectivity', 'network performance', 'common issues'] },
        ],
    },
    'a+': {
        slug: 'a-plus',
        name: 'CompTIA A+ (220-1101 & 220-1102)',
        issuer: 'CompTIA',
        domains: [
            { id: 'mh', name: 'Mobile Devices, Hardware & Networking', weight: '30%', topics: ['mobile devices', 'hardware', 'networking', 'printers', 'virtualization', 'cloud computing'] },
            { id: 'os', name: 'Operating Systems', weight: '27%', topics: ['Windows', 'macOS', 'Linux', 'installation', 'command line', 'features'] },
            { id: 'st', name: 'Security & Troubleshooting', weight: '25%', topics: ['security threats', 'security best practices', 'troubleshooting methodology', 'hardware troubleshooting'] },
            { id: 'op', name: 'Operational Procedures', weight: '18%', topics: ['documentation', 'change management', 'disaster recovery', 'scripting', 'remote access', 'professionalism'] },
        ],
    },
    'linux+': {
        slug: 'linux-plus',
        name: 'CompTIA Linux+ (XK0-005)',
        issuer: 'CompTIA',
        domains: [
            { id: 'sa', name: 'System Management', weight: '32%', topics: ['system boot', 'kernel modules', 'package management', 'process management', 'storage', 'filesystem'] },
            { id: 'sc', name: 'Security', weight: '21%', topics: ['permissions', 'SELinux', 'AppArmor', 'firewalls', 'SSH', 'PAM', 'auditing'] },
            { id: 'str', name: 'Scripting, Containers & Automation', weight: '19%', topics: ['bash scripting', 'Docker', 'orchestration', 'cron', 'Ansible', 'cloud-init'] },
            { id: 'ts', name: 'Troubleshooting', weight: '28%', topics: ['system logs', 'network troubleshooting', 'storage issues', 'performance tuning'] },
        ],
    },
    'cloud+': {
        slug: 'cloud-plus',
        name: 'CompTIA Cloud+ (CV0-004)',
        issuer: 'CompTIA',
        domains: [
            { id: 'cc', name: 'Cloud Architecture and Design', weight: '13%', topics: ['cloud models', 'design principles', 'capacity planning'] },
            { id: 'ds', name: 'Data Center Infrastructure', weight: '10%', topics: ['compute', 'storage', 'networking hardware'] },
            { id: 'ms', name: 'Storage Solutions', weight: '11%', topics: ['block storage', 'object storage', 'file storage', 'tiering'] },
            { id: 'ni', name: 'Network Infrastructure', weight: '11%', topics: ['SDN', 'VPN', 'load balancing', 'DNS'] },
            { id: 'si', name: 'Security', weight: '22%', topics: ['IAM', 'encryption', 'compliance', 'hardening'] },
            { id: 'mig', name: 'Cloud Migration', weight: '10%', topics: ['migration strategies', 'P2V', 'testing'] },
            { id: 'ts', name: 'Troubleshooting', weight: '23%', topics: ['connectivity', 'performance', 'availability'] },
        ],
    },
    'cysa+': {
        slug: 'cysa-plus',
        name: 'CompTIA CySA+ (CS0-003)',
        issuer: 'CompTIA',
        domains: [
            { id: 'sm', name: 'Security Operations', weight: '33%', topics: ['SIEM', 'log analysis', 'threat intelligence', 'SOC operations'] },
            { id: 'vam', name: 'Vulnerability Management', weight: '30%', topics: ['scanning', 'remediation', 'risk scoring', 'asset inventory'] },
            { id: 'ir', name: 'Incident Response Management', weight: '20%', topics: ['IR lifecycle', 'containment', 'eradication', 'forensics'] },
            { id: 'rc', name: 'Reporting and Communication', weight: '17%', topics: ['metrics', 'KPIs', 'stakeholder communication', 'compliance reporting'] },
        ],
    },
    'pentest+': {
        slug: 'pentest-plus',
        name: 'CompTIA PenTest+ (PT0-003)',
        issuer: 'CompTIA',
        domains: [
            { id: 'pp', name: 'Engagement Management', weight: '22%', topics: ['scoping', 'rules of engagement', 'legal compliance', 'reporting'] },
            { id: 'ra', name: 'Reconnaissance and Enumeration', weight: '18%', topics: ['OSINT', 'active scanning', 'Nmap', 'DNS enumeration'] },
            { id: 'av', name: 'Attacks and Exploits', weight: '30%', topics: ['social engineering', 'web app attacks', 'wireless attacks', 'privilege escalation'] },
            { id: 'rp', name: 'Reporting and Communication', weight: '16%', topics: ['findings documentation', 'remediation recommendations', 'executive summary'] },
            { id: 'to', name: 'Tools and Code Analysis', weight: '14%', topics: ['Metasploit', 'Burp Suite', 'scripting', 'code review'] },
        ],
    },
    'casp+': {
        slug: 'casp-plus',
        name: 'CompTIA CASP+ (CAS-004)',
        issuer: 'CompTIA',
        domains: [
            { id: 'se', name: 'Security Architecture', weight: '29%', topics: ['enterprise security', 'zero trust', 'cloud architecture', 'crypto systems'] },
            { id: 'so', name: 'Security Operations', weight: '30%', topics: ['threat management', 'vulnerability management', 'IR', 'forensics'] },
            { id: 'gcrc', name: 'Governance, Risk, and Compliance', weight: '20%', topics: ['risk strategies', 'compliance frameworks', 'policies'] },
            { id: 'cr', name: 'Security Engineering and Cryptography', weight: '21%', topics: ['PKI', 'crypto protocols', 'secure protocols', 'key management'] },
        ],
    },
    // ── ISACA ──
    cisa: {
        slug: 'cisa',
        name: 'CISA (Certified Information Systems Auditor)',
        issuer: 'ISACA',
        domains: [
            { id: 'isp', name: 'Information Systems Auditing Process', weight: '18%', topics: ['audit planning', 'audit execution', 'audit governance', 'reporting', 'follow-up'] },
            { id: 'git', name: 'Governance and Management of IT', weight: '18%', topics: ['IT governance', 'IT management frameworks', 'IT resource management', 'IT service management', 'quality assurance'] },
            { id: 'isd', name: 'IS Acquisition, Development and Implementation', weight: '12%', topics: ['project governance', 'project management', 'IS development methodologies', 'IS maintenance'] },
            { id: 'iso', name: 'IS Operations and Business Resilience', weight: '26%', topics: ['IS operations', 'hardware', 'IS architecture', 'data governance', 'BCP/DRP'] },
            { id: 'pia', name: 'Protection of Information Assets', weight: '26%', topics: ['security frameworks', 'access control', 'network security', 'data classification', 'physical security', 'encryption'] },
        ],
    },
    cism: {
        slug: 'cism',
        name: 'CISM (Certified Information Security Manager)',
        issuer: 'ISACA',
        domains: [
            { id: 'isg', name: 'Information Security Governance', weight: '17%', topics: ['governance framework', 'security strategy', 'governance metrics', 'resource management'] },
            { id: 'irm', name: 'Information Risk Management', weight: '20%', topics: ['risk identification', 'risk assessment', 'risk response', 'risk monitoring', 'risk reporting'] },
            { id: 'isdm', name: 'Information Security Program', weight: '33%', topics: ['program development', 'program management', 'program resources', 'security architectures'] },
            { id: 'isim', name: 'Incident Management', weight: '30%', topics: ['incident classification', 'incident management', 'investigation', 'response planning', 'recovery'] },
        ],
    },
    crisc: {
        slug: 'crisc',
        name: 'CRISC (Certified in Risk and Information Systems Control)',
        issuer: 'ISACA',
        domains: [
            { id: 'grc', name: 'Governance, Risk, and Control', weight: '26%', topics: ['IT governance', 'risk governance', 'control frameworks', 'organizational structure'] },
            { id: 'it', name: 'IT Risk Assessment', weight: '20%', topics: ['risk identification', 'risk scenarios', 'risk analysis', 'risk evaluation'] },
            { id: 'rr', name: 'Risk Response and Reporting', weight: '32%', topics: ['risk response options', 'risk treatment', 'risk reporting', 'KRIs'] },
            { id: 'ti', name: 'Technology and Security', weight: '22%', topics: ['IS controls', 'security technologies', 'monitoring tools'] },
        ],
    },
    cgeit: {
        slug: 'cgeit',
        name: 'CGEIT (Certified in the Governance of Enterprise IT)',
        issuer: 'ISACA',
        domains: [
            { id: 'gf', name: 'Governance of Enterprise IT Framework', weight: '25%', topics: ['governance principles', 'organizational structures', 'COBIT'] },
            { id: 'sm', name: 'Strategic Management', weight: '20%', topics: ['strategic planning', 'IT strategy alignment', 'value delivery'] },
            { id: 'bm', name: 'Benefits Realization', weight: '16%', topics: ['benefits management', 'value measurement', 'portfolio management'] },
            { id: 'ro', name: 'Risk Optimization', weight: '24%', topics: ['risk appetite', 'risk assessment', 'risk optimization'] },
            { id: 'ro2', name: 'Resource Optimization', weight: '15%', topics: ['resource management', 'capability assessment', 'sourcing'] },
        ],
    },
    // ── EC-Council ──
    ceh: {
        slug: 'ceh',
        name: 'CEH (Certified Ethical Hacker) v13',
        issuer: 'EC-Council',
        domains: [
            { id: 'ie', name: 'Introduction to Ethical Hacking', weight: '6%', topics: ['hacking methodology', 'attack vectors', 'information security laws'] },
            { id: 'fr', name: 'Footprinting and Reconnaissance', weight: '9%', topics: ['OSINT', 'DNS footprinting', 'network scanning', 'social engineering recon'] },
            { id: 'se', name: 'Scanning Networks and Enumeration', weight: '9%', topics: ['Nmap', 'port scanning', 'SNMP enumeration', 'LDAP enumeration'] },
            { id: 'va', name: 'Vulnerability Analysis', weight: '7%', topics: ['vulnerability scoring', 'CVE', 'Nessus', 'OpenVAS'] },
            { id: 'sh', name: 'System Hacking', weight: '12%', topics: ['password cracking', 'privilege escalation', 'rootkits', 'steganography'] },
            { id: 'mal', name: 'Malware Threats', weight: '9%', topics: ['trojans', 'viruses', 'worms', 'ransomware', 'fileless malware'] },
            { id: 'sn', name: 'Sniffing & Social Engineering', weight: '10%', topics: ['Wireshark', 'ARP poisoning', 'phishing', 'pretexting'] },
            { id: 'wd', name: 'Hacking Web Servers & Web Apps', weight: '11%', topics: ['OWASP Top 10', 'SQL injection', 'XSS', 'CSRF', 'Burp Suite'] },
            { id: 'wl', name: 'Wireless & IoT Hacking', weight: '8%', topics: ['WPA3 cracking', 'rogue AP', 'Bluetooth attacks', 'IoT vulnerabilities'] },
            { id: 'cr', name: 'Cryptography', weight: '9%', topics: ['symmetric/asymmetric encryption', 'PKI', 'hash algorithms', 'crypto attacks'] },
            { id: 'ch', name: 'Cloud & Session Hijacking', weight: '10%', topics: ['cloud security', 'container security', 'session fixation', 'token manipulation'] },
        ],
    },
    chfi: {
        slug: 'chfi',
        name: 'CHFI (Computer Hacking Forensic Investigator) v11',
        issuer: 'EC-Council',
        domains: [
            { id: 'cf', name: 'Computer Forensics Fundamentals', weight: '10%', topics: ['forensics methodology', 'legal considerations', 'chain of custody'] },
            { id: 'fi', name: 'Forensics Investigation Process', weight: '12%', topics: ['evidence acquisition', 'imaging', 'analysis workflow'] },
            { id: 'hdf', name: 'Hard Disk and File Systems Forensics', weight: '15%', topics: ['NTFS', 'ext4', 'FAT', 'data recovery', 'slack space'] },
            { id: 'of', name: 'Operating System Forensics', weight: '15%', topics: ['Windows forensics', 'Linux forensics', 'registry analysis', 'log analysis'] },
            { id: 'nf', name: 'Network and Cloud Forensics', weight: '15%', topics: ['packet analysis', 'network logs', 'cloud evidence', 'VPN forensics'] },
            { id: 'mf', name: 'Malware Forensics', weight: '10%', topics: ['static analysis', 'dynamic analysis', 'reverse engineering'] },
            { id: 'wf', name: 'Web Forensics', weight: '8%', topics: ['browser forensics', 'server logs', 'web application attacks'] },
            { id: 'df', name: 'Database Forensics', weight: '8%', topics: ['SQL analysis', 'transaction logs', 'data manipulation detection'] },
            { id: 'ef', name: 'Email and Mobile Forensics', weight: '7%', topics: ['email headers', 'mobile acquisition', 'app data extraction'] },
        ],
    },
    // ── AWS ──
    'aws-saa': {
        slug: 'aws-saa',
        name: 'AWS Solutions Architect Associate (SAA-C03)',
        issuer: 'Amazon Web Services',
        domains: [
            { id: 'sra', name: 'Design Secure Architectures', weight: '30%', topics: ['IAM', 'VPC', 'security groups', 'NACLs', 'encryption', 'AWS Organizations', 'WAF', 'Shield'] },
            { id: 'hra', name: 'Design Resilient Architectures', weight: '26%', topics: ['multi-tier architectures', 'high availability', 'fault tolerance', 'decoupling', 'auto scaling', 'disaster recovery'] },
            { id: 'hpa', name: 'Design High-Performing Architectures', weight: '24%', topics: ['compute', 'storage', 'databases', 'networking', 'caching', 'content delivery'] },
            { id: 'coa', name: 'Design Cost-Optimized Architectures', weight: '20%', topics: ['cost-effective resources', 'pricing models', 'reserved instances', 'spot instances', 'storage tiering'] },
        ],
    },
    'aws-dev': {
        slug: 'aws-dev',
        name: 'AWS Certified Developer Associate (DVA-C02)',
        issuer: 'Amazon Web Services',
        domains: [
            { id: 'dc', name: 'Development with AWS Services', weight: '32%', topics: ['Lambda', 'API Gateway', 'DynamoDB', 'S3', 'SQS', 'SNS', 'Step Functions'] },
            { id: 'sc', name: 'Security', weight: '26%', topics: ['IAM', 'Cognito', 'KMS', 'Secrets Manager', 'encryption'] },
            { id: 'di', name: 'Deployment', weight: '24%', topics: ['CodePipeline', 'CodeBuild', 'CodeDeploy', 'CloudFormation', 'SAM', 'CDK'] },
            { id: 'tr', name: 'Troubleshooting and Optimization', weight: '18%', topics: ['CloudWatch', 'X-Ray', 'performance tuning', 'caching strategies'] },
        ],
    },
    'aws-sysops': {
        slug: 'aws-sysops',
        name: 'AWS SysOps Administrator Associate (SOA-C02)',
        issuer: 'Amazon Web Services',
        domains: [
            { id: 'mo', name: 'Monitoring, Logging, and Remediation', weight: '20%', topics: ['CloudWatch', 'CloudTrail', 'Config', 'EventBridge', 'alarms'] },
            { id: 'rel', name: 'Reliability and Business Continuity', weight: '16%', topics: ['backup', 'DR strategies', 'fault tolerance', 'multi-AZ'] },
            { id: 'dep', name: 'Deployment, Provisioning, and Automation', weight: '18%', topics: ['CloudFormation', 'Systems Manager', 'OpsWorks', 'Elastic Beanstalk'] },
            { id: 'sec', name: 'Security and Compliance', weight: '16%', topics: ['IAM', 'GuardDuty', 'Inspector', 'compliance frameworks'] },
            { id: 'net', name: 'Networking and Content Delivery', weight: '18%', topics: ['VPC', 'Route 53', 'CloudFront', 'Direct Connect', 'ELB'] },
            { id: 'co', name: 'Cost and Performance Optimization', weight: '12%', topics: ['Cost Explorer', 'Trusted Advisor', 'right-sizing', 'reserved capacity'] },
        ],
    },
    'aws-security': {
        slug: 'aws-security',
        name: 'AWS Certified Security Specialty (SCS-C02)',
        issuer: 'Amazon Web Services',
        domains: [
            { id: 'ti', name: 'Threat Detection and Incident Response', weight: '14%', topics: ['GuardDuty', 'Security Hub', 'Detective', 'IR procedures'] },
            { id: 'sl', name: 'Security Logging and Monitoring', weight: '18%', topics: ['CloudTrail', 'CloudWatch Logs', 'VPC Flow Logs', 'S3 access logs'] },
            { id: 'im', name: 'Infrastructure Security', weight: '20%', topics: ['VPC security', 'WAF', 'Shield', 'network segmentation'] },
            { id: 'iac', name: 'Identity and Access Management', weight: '16%', topics: ['IAM policies', 'STS', 'Organizations', 'SSO', 'federation'] },
            { id: 'dp', name: 'Data Protection', weight: '18%', topics: ['KMS', 'CloudHSM', 'ACM', 'encryption at rest/transit'] },
            { id: 'mp', name: 'Management and Security Governance', weight: '14%', topics: ['AWS Config', 'Service Control Policies', 'compliance'] },
        ],
    },
    'aws-cloud-practitioner': {
        slug: 'aws-cloud-practitioner',
        name: 'AWS Cloud Practitioner (CLF-C02)',
        issuer: 'Amazon Web Services',
        domains: [
            { id: 'cc', name: 'Cloud Concepts', weight: '24%', topics: ['cloud benefits', 'cloud economics', 'cloud architecture principles'] },
            { id: 'sc', name: 'Security and Compliance', weight: '30%', topics: ['shared responsibility model', 'IAM basics', 'compliance programs'] },
            { id: 'ct', name: 'Cloud Technology and Services', weight: '34%', topics: ['core services', 'compute', 'storage', 'database', 'networking'] },
            { id: 'cb', name: 'Billing, Pricing, and Support', weight: '12%', topics: ['pricing models', 'billing tools', 'support plans'] },
        ],
    },
    // ── Azure ──
    'az-900': {
        slug: 'az-900',
        name: 'Microsoft Azure Fundamentals (AZ-900)',
        issuer: 'Microsoft',
        domains: [
            { id: 'cc', name: 'Cloud Concepts', weight: '25%', topics: ['cloud computing benefits', 'service types (IaaS, PaaS, SaaS)', 'cloud models (public, private, hybrid)'] },
            { id: 'aa', name: 'Azure Architecture and Services', weight: '35%', topics: ['core resources', 'compute', 'networking', 'storage', 'identity & security', 'governance'] },
            { id: 'am', name: 'Azure Management and Governance', weight: '30%', topics: ['cost management', 'governance tools', 'monitoring', 'Azure Resource Manager', 'Azure Arc'] },
            { id: 'as', name: 'Azure Security', weight: '10%', topics: ['Entra ID', 'MFA', 'RBAC', 'Azure Policy', 'network security'] },
        ],
    },
    'az-104': {
        slug: 'az-104',
        name: 'Microsoft Azure Administrator (AZ-104)',
        issuer: 'Microsoft',
        domains: [
            { id: 'im', name: 'Manage Azure Identities and Governance', weight: '20-25%', topics: ['Entra ID', 'RBAC', 'Azure Policy', 'resource locks', 'management groups'] },
            { id: 'str', name: 'Implement and Manage Storage', weight: '15-20%', topics: ['storage accounts', 'blob storage', 'Azure Files', 'storage security'] },
            { id: 'vm', name: 'Deploy and Manage Azure Compute Resources', weight: '20-25%', topics: ['VMs', 'App Service', 'containers', 'AKS'] },
            { id: 'net', name: 'Implement and Manage Virtual Networking', weight: '15-20%', topics: ['VNet', 'NSG', 'Azure DNS', 'peering', 'load balancers'] },
            { id: 'mon', name: 'Monitor and Maintain Azure Resources', weight: '10-15%', topics: ['Azure Monitor', 'Log Analytics', 'alerts', 'backup'] },
        ],
    },
    'az-204': {
        slug: 'az-204',
        name: 'Microsoft Azure Developer Associate (AZ-204)',
        issuer: 'Microsoft',
        domains: [
            { id: 'ac', name: 'Develop Azure Compute Solutions', weight: '25-30%', topics: ['Azure Functions', 'App Service', 'containers', 'ACI'] },
            { id: 'as', name: 'Develop for Azure Storage', weight: '15-20%', topics: ['Cosmos DB', 'Blob Storage', 'Table Storage'] },
            { id: 'ai', name: 'Implement Azure Security', weight: '20-25%', topics: ['Microsoft Identity Platform', 'Managed Identity', 'Key Vault'] },
            { id: 'mo', name: 'Monitor, Troubleshoot, and Optimize', weight: '15-20%', topics: ['Application Insights', 'caching', 'CDN'] },
            { id: 'cs', name: 'Connect to and Consume Azure Services', weight: '15-20%', topics: ['API Management', 'Event Grid', 'Service Bus', 'Queue Storage'] },
        ],
    },
    'az-305': {
        slug: 'az-305',
        name: 'Microsoft Azure Solutions Architect Expert (AZ-305)',
        issuer: 'Microsoft',
        domains: [
            { id: 'id', name: 'Design Identity, Governance, and Monitoring', weight: '25-30%', topics: ['Entra ID', 'governance', 'monitoring strategy', 'logging'] },
            { id: 'ds', name: 'Design Data Storage Solutions', weight: '25-30%', topics: ['relational data', 'non-relational data', 'data integration'] },
            { id: 'bc', name: 'Design Business Continuity Solutions', weight: '10-15%', topics: ['backup', 'DR', 'high availability'] },
            { id: 'inf', name: 'Design Infrastructure Solutions', weight: '25-30%', topics: ['compute', 'application architecture', 'network', 'migrations'] },
        ],
    },
    'sc-900': {
        slug: 'sc-900',
        name: 'Microsoft Security, Compliance & Identity Fundamentals (SC-900)',
        issuer: 'Microsoft',
        domains: [
            { id: 'sc', name: 'Security, Compliance, Identity Concepts', weight: '10-15%', topics: ['shared responsibility', 'defense in depth', 'Zero Trust', 'encryption'] },
            { id: 'ms', name: 'Microsoft Entra (Azure AD)', weight: '25-30%', topics: ['identity concepts', 'authentication methods', 'access management', 'identity protection'] },
            { id: 'df', name: 'Microsoft Defender & Security Solutions', weight: '25-30%', topics: ['Defender for Cloud', 'Sentinel', 'Defender for Endpoint', 'DDoS Protection'] },
            { id: 'pc', name: 'Microsoft Purview Compliance', weight: '25-30%', topics: ['compliance portal', 'information protection', 'data lifecycle', 'insider risk', 'eDiscovery'] },
        ],
    },
    'ai-900': {
        slug: 'ai-900',
        name: 'Microsoft Azure AI Fundamentals (AI-900)',
        issuer: 'Microsoft',
        domains: [
            { id: 'ai', name: 'AI and Machine Learning Concepts', weight: '15-20%', topics: ['ML types', 'regression', 'classification', 'clustering', 'deep learning'] },
            { id: 'cv', name: 'Computer Vision Workloads', weight: '15-20%', topics: ['image classification', 'object detection', 'OCR', 'Azure Computer Vision'] },
            { id: 'nl', name: 'Natural Language Processing Workloads', weight: '15-20%', topics: ['text analytics', 'translation', 'LUIS', 'Azure AI Language'] },
            { id: 'ga', name: 'Generative AI Workloads', weight: '15-20%', topics: ['Azure OpenAI Service', 'prompt engineering', 'responsible AI'] },
            { id: 'sr', name: 'Document Intelligence and Knowledge Mining', weight: '15-20%', topics: ['Azure AI Document Intelligence', 'cognitive search', 'knowledge stores'] },
        ],
    },
    // ── GCP ──
    'gcp-pca': {
        slug: 'gcp-pca',
        name: 'Google Professional Cloud Architect',
        issuer: 'Google Cloud',
        domains: [
            { id: 'cd', name: 'Designing Cloud Solutions', weight: '30%', topics: ['compute options', 'data solutions', 'networking', 'migration planning'] },
            { id: 'ma', name: 'Managing and Provisioning Cloud Infrastructure', weight: '26%', topics: ['Compute Engine', 'GKE', 'Cloud Functions', 'Terraform'] },
            { id: 'co', name: 'Designing for Security and Compliance', weight: '22%', topics: ['IAM', 'VPC security', 'data encryption', 'compliance'] },
            { id: 'ao', name: 'Analyzing and Optimizing Technical Processes', weight: '22%', topics: ['CI/CD', 'monitoring', 'cost optimization', 'SRE'] },
        ],
    },
    'gcp-ace': {
        slug: 'gcp-ace',
        name: 'Google Associate Cloud Engineer',
        issuer: 'Google Cloud',
        domains: [
            { id: 'sp', name: 'Setting Up a Cloud Solution Environment', weight: '20%', topics: ['projects', 'billing', 'IAM', 'APIs'] },
            { id: 'pi', name: 'Planning and Configuring a Cloud Solution', weight: '15%', topics: ['pricing calculator', 'compute sizing', 'network planning'] },
            { id: 'dc', name: 'Deploying and Implementing a Cloud Solution', weight: '25%', topics: ['Compute Engine', 'GKE', 'App Engine', 'Cloud Run', 'Cloud Functions'] },
            { id: 'sc', name: 'Ensuring Successful Operation of Cloud Solution', weight: '20%', topics: ['Cloud Monitoring', 'Cloud Logging', 'troubleshooting'] },
            { id: 'co', name: 'Configuring Access and Security', weight: '20%', topics: ['IAM policies', 'service accounts', 'VPC firewalls'] },
        ],
    },
    // ── PMI ──
    pmp: {
        slug: 'pmp',
        name: 'PMP (Project Management Professional)',
        issuer: 'PMI',
        domains: [
            { id: 'pe', name: 'People (Leadership)', weight: '42%', topics: ['team building', 'conflict resolution', 'servant leadership', 'stakeholder engagement', 'emotional intelligence', 'virtual teams'] },
            { id: 'pr', name: 'Process', weight: '50%', topics: ['planning', 'scope management', 'schedule', 'cost', 'quality', 'resource', 'communications', 'risk', 'procurement', 'agile/hybrid approaches'] },
            { id: 'be', name: 'Business Environment', weight: '8%', topics: ['benefits realization', 'organizational change', 'compliance', 'project selection'] },
        ],
    },
    capm: {
        slug: 'capm',
        name: 'CAPM (Certified Associate in Project Management)',
        issuer: 'PMI',
        domains: [
            { id: 'pm', name: 'Project Management Fundamentals', weight: '17%', topics: ['project lifecycle', 'project vs operations', 'PMO', 'organizational structures'] },
            { id: 'pp', name: 'Predictive Plan-Based Methodologies', weight: '26%', topics: ['WBS', 'critical path', 'earned value', 'Gantt charts'] },
            { id: 'ag', name: 'Agile Frameworks/Methodologies', weight: '20%', topics: ['Scrum', 'Kanban', 'XP', 'user stories', 'velocity'] },
            { id: 'ba', name: 'Business Analysis Frameworks', weight: '37%', topics: ['requirements analysis', 'stakeholder analysis', 'traceability', 'business case'] },
        ],
    },
    // ── Kubernetes & DevOps ──
    cka: {
        slug: 'cka',
        name: 'CKA (Certified Kubernetes Administrator)',
        issuer: 'Linux Foundation / CNCF',
        domains: [
            { id: 'ca', name: 'Cluster Architecture, Installation & Configuration', weight: '25%', topics: ['kubeadm', 'etcd', 'RBAC', 'upgrade procedures', 'HA clusters'] },
            { id: 'wl', name: 'Workloads & Scheduling', weight: '15%', topics: ['Deployments', 'DaemonSets', 'Jobs', 'CronJobs', 'resource limits', 'node affinity'] },
            { id: 'sn', name: 'Services & Networking', weight: '20%', topics: ['Services', 'Ingress', 'NetworkPolicies', 'DNS', 'CNI'] },
            { id: 'str', name: 'Storage', weight: '10%', topics: ['PV', 'PVC', 'StorageClasses', 'CSI drivers'] },
            { id: 'ts', name: 'Troubleshooting', weight: '30%', topics: ['logging', 'cluster troubleshooting', 'node issues', 'network debugging'] },
        ],
    },
    ckad: {
        slug: 'ckad',
        name: 'CKAD (Certified Kubernetes Application Developer)',
        issuer: 'Linux Foundation / CNCF',
        domains: [
            { id: 'ac', name: 'Application Design and Build', weight: '20%', topics: ['multi-container pods', 'init containers', 'volumes', 'ConfigMaps', 'Secrets'] },
            { id: 'ad', name: 'Application Deployment', weight: '20%', topics: ['Deployments', 'rolling updates', 'rollbacks', 'Helm', 'Kustomize'] },
            { id: 'ao', name: 'Application Observability and Maintenance', weight: '15%', topics: ['probes', 'logging', 'debugging', 'resource usage'] },
            { id: 'ae', name: 'Application Environment, Configuration & Security', weight: '25%', topics: ['SecurityContext', 'ServiceAccounts', 'NetworkPolicies', 'resource quotas'] },
            { id: 'sn', name: 'Services and Networking', weight: '20%', topics: ['Services', 'Ingress', 'NetworkPolicies'] },
        ],
    },
    terraform: {
        slug: 'terraform',
        name: 'HashiCorp Terraform Associate (003)',
        issuer: 'HashiCorp',
        domains: [
            { id: 'ic', name: 'IaC Concepts', weight: '14%', topics: ['IaC benefits', 'declarative vs imperative', 'idempotency'] },
            { id: 'tf', name: 'Terraform Purpose', weight: '9%', topics: ['multi-cloud', 'provider ecosystem', 'Terraform vs alternatives'] },
            { id: 'ba', name: 'Terraform Basics', weight: '32%', topics: ['providers', 'resources', 'variables', 'outputs', 'data sources', 'expressions', 'functions'] },
            { id: 'co', name: 'Terraform Core Workflow', weight: '14%', topics: ['init', 'plan', 'apply', 'destroy', 'workspaces'] },
            { id: 'ms', name: 'Modules and State', weight: '21%', topics: ['module sources', 'state backends', 'state locking', 'import'] },
            { id: 'cs', name: 'Configuration Sharing', weight: '10%', topics: ['Terraform Registry', 'Terraform Cloud', 'Sentinel'] },
        ],
    },
    // ── Scrum ──
    psm: {
        slug: 'psm',
        name: 'PSM I (Professional Scrum Master)',
        issuer: 'Scrum.org',
        domains: [
            { id: 'sf', name: 'Scrum Framework', weight: '30%', topics: ['Sprint', 'events', 'artifacts', 'commitments', 'Scrum Guide 2020'] },
            { id: 'st', name: 'Scrum Theory and Principles', weight: '25%', topics: ['empiricism', 'transparency', 'inspection', 'adaptation', 'Scrum values'] },
            { id: 'sm', name: 'Scrum Master Role', weight: '25%', topics: ['servant leadership', 'facilitation', 'coaching', 'impediment removal'] },
            { id: 'sp', name: 'Scrum Practices', weight: '20%', topics: ['Sprint Planning', 'Daily Scrum', 'Sprint Review', 'Sprint Retrospective', 'Product Backlog refinement'] },
        ],
    },
    // ── Compliance & Frameworks ──
    'iso-27001-la': {
        slug: 'iso-27001-la',
        name: 'ISO 27001 Lead Auditor',
        issuer: 'PECB / BSI',
        domains: [
            { id: 'isms', name: 'ISMS Fundamentals and Standards', weight: '25%', topics: ['ISO 27001 requirements', 'ISO 27002 controls', 'ISMS scope', 'risk treatment'] },
            { id: 'pa', name: 'Planning an ISO 27001 Audit', weight: '20%', topics: ['audit planning', 'audit criteria', 'audit team', 'audit schedule'] },
            { id: 'ca', name: 'Conducting an ISO 27001 Audit', weight: '30%', topics: ['opening meeting', 'evidence collection', 'audit findings', 'nonconformities'] },
            { id: 'cra', name: 'Closing and Reporting the Audit', weight: '15%', topics: ['audit report', 'closing meeting', 'corrective actions'] },
            { id: 'ma', name: 'Managing an Internal Audit Program', weight: '10%', topics: ['audit program management', 'competence evaluation', 'continual improvement'] },
        ],
    },
    'gdpr-practitioner': {
        slug: 'gdpr-practitioner',
        name: 'GDPR Practitioner',
        issuer: 'BCS / IAPP',
        domains: [
            { id: 'gf', name: 'GDPR Foundations and Scope', weight: '20%', topics: ['GDPR articles', 'territorial scope', 'key definitions', 'lawful basis'] },
            { id: 'lr', name: 'Lawful Bases and Rights', weight: '25%', topics: ['consent', 'legitimate interest', 'data subject rights', 'DSAR'] },
            { id: 'dc', name: 'Data Controller Obligations', weight: '25%', topics: ['DPO', 'DPIA', 'records of processing', 'international transfers'] },
            { id: 'dp', name: 'Data Protection by Design', weight: '15%', topics: ['privacy by design', 'pseudonymization', 'anonymization', 'data minimization'] },
            { id: 'ir', name: 'Incidents and Breaches', weight: '15%', topics: ['breach notification', 'supervisory authority', 'penalties', 'remediation'] },
        ],
    },
    hipaa: {
        slug: 'hipaa',
        name: 'HIPAA Compliance Training',
        issuer: 'HHS / AHIMA',
        domains: [
            { id: 'pr', name: 'Privacy Rule', weight: '30%', topics: ['PHI', 'minimum necessary', 'authorizations', 'disclosures', 'patient rights'] },
            { id: 'sr', name: 'Security Rule', weight: '30%', topics: ['administrative safeguards', 'physical safeguards', 'technical safeguards', 'risk analysis'] },
            { id: 'br', name: 'Breach Notification Rule', weight: '15%', topics: ['breach definition', 'notification requirements', 'risk assessment', 'safe harbor'] },
            { id: 'en', name: 'Enforcement and Penalties', weight: '10%', topics: ['OCR enforcement', 'civil penalties', 'criminal penalties', 'corrective action plans'] },
            { id: 'co', name: 'Covered Entities and Business Associates', weight: '15%', topics: ['covered entity types', 'BAAs', 'subcontractors', 'liability'] },
        ],
    },
    // ── Brasil ──
    enem: {
        slug: 'enem',
        name: 'Exame Nacional do Ensino Médio (ENEM)',
        issuer: 'INEP',
        domains: [
            { id: 'ling', name: 'Linguagens, Códigos e suas Tecnologias', weight: '25%', topics: ['Língua Portuguesa', 'Literatura', 'Língua Estrangeira', 'Artes', 'Educação Física', 'Tecnologias da Informação'] },
            { id: 'mat', name: 'Matemática e suas Tecnologias', weight: '25%', topics: ['Números e Operações', 'Geometria', 'Álgebra', 'Análise de Dados', 'Raciocínio Lógico'] },
            { id: 'ci1', name: 'Ciências da Natureza e suas Tecnologias', weight: '25%', topics: ['Biologia', 'Química', 'Física', 'Ciências Ambientais'] },
            { id: 'ci2', name: 'Ciências Humanas e suas Tecnologias', weight: '25%', topics: ['História', 'Geografia', 'Filosofia', 'Sociologia'] },
        ],
    },
    'oab-primeira-fase': {
        slug: 'oab-primeira-fase',
        name: 'OAB Primeira Fase',
        issuer: 'Conselho Federal da OAB',
        domains: [
            { id: 'cc', name: 'Direito Constitucional', weight: '12%', topics: ['direitos fundamentais', 'organização do Estado', 'controle de constitucionalidade', 'remédios constitucionais'] },
            { id: 'cp', name: 'Direito Penal e Processual Penal', weight: '16%', topics: ['teoria do crime', 'excludentes', 'penas', 'processo penal', 'recursos'] },
            { id: 'cv', name: 'Direito Civil e Processual Civil', weight: '18%', topics: ['obrigações', 'contratos', 'responsabilidade civil', 'processo de conhecimento', 'recursos'] },
            { id: 'ct', name: 'Direito do Trabalho e Processual do Trabalho', weight: '14%', topics: ['CLT', 'contrato de trabalho', 'rescisão', 'processo trabalhista'] },
            { id: 'et', name: 'Ética e Estatuto da OAB', weight: '15%', topics: ['Estatuto da OAB', 'Código de Ética', 'direitos e deveres do advogado', 'infrações disciplinares'] },
            { id: 'ta', name: 'Direito Tributário e Administrativo', weight: '12%', topics: ['tributos', 'obrigação tributária', 'licitações', 'atos administrativos'] },
            { id: 'em', name: 'Direito Empresarial', weight: '8%', topics: ['sociedades', 'títulos de crédito', 'falência', 'recuperação judicial'] },
            { id: 'ou', name: 'Direito do Consumidor e outros', weight: '5%', topics: ['CDC', 'direitos difusos', 'ECA', 'direito ambiental'] },
        ],
    },
    'residencia-medica': {
        slug: 'residencia-medica',
        name: 'Residência Médica (FAMERP / USP / UNIFESP)',
        issuer: 'Diversas Instituições BR',
        domains: [
            { id: 'cl', name: 'Clínica Médica', weight: '30%', topics: ['cardiologia', 'pneumologia', 'endocrinologia', 'nefrologia', 'infectologia', 'emergências clínicas'] },
            { id: 'cg', name: 'Cirurgia Geral', weight: '20%', topics: ['trauma', 'abdome agudo', 'hérnias', 'cirurgia oncológica', 'pré e pós-operatório'] },
            { id: 'ob', name: 'Obstetrícia e Ginecologia', weight: '15%', topics: ['pré-natal', 'parto', 'puerpério', 'patologias ginecológicas', 'anticoncepção'] },
            { id: 'pe', name: 'Pediatria', weight: '15%', topics: ['puericultura', 'infecções pediátricas', 'neonatologia', 'vacinação', 'emergências pediátricas'] },
            { id: 'pm', name: 'Medicina Preventiva e Saúde Pública', weight: '10%', topics: ['epidemiologia', 'SUS', 'ESF', 'vigilância sanitária', 'indicadores de saúde'] },
            { id: 'ou', name: 'Outras especialidades', weight: '10%', topics: ['ortopedia', 'oftalmologia', 'dermatologia', 'psiquiatria', 'otorrinolaringologia'] },
        ],
    },
};

// ── Aliases for flexible matching ──

export const CERT_ALIASES: Record<string, string> = {
    cissp: 'cissp', cc: 'cc', sscp: 'sscp', ccsp: 'ccsp', cgrc: 'cgrc', hcispp: 'hcispp',
    'security+': 'security+', securityplus: 'security+', 'sec+': 'security+', 'comptia security+': 'security+', 'sy0-701': 'security+',
    'network+': 'network+', networkplus: 'network+', 'net+': 'network+', 'n10-009': 'network+',
    'a+': 'a+', aplus: 'a+', 'comptia a+': 'a+',
    'linux+': 'linux+', linuxplus: 'linux+', 'xk0-005': 'linux+',
    'cloud+': 'cloud+', cloudplus: 'cloud+',
    'cysa+': 'cysa+', cysaplus: 'cysa+',
    'pentest+': 'pentest+', pentestplus: 'pentest+',
    'casp+': 'casp+', caspplus: 'casp+',
    cisa: 'cisa', cism: 'cism', crisc: 'crisc', cgeit: 'cgeit',
    ceh: 'ceh', chfi: 'chfi',
    'aws-saa': 'aws-saa', 'aws saa': 'aws-saa', 'aws solutions architect': 'aws-saa', 'saa-c03': 'aws-saa',
    'aws-dev': 'aws-dev', 'dva-c02': 'aws-dev',
    'aws-sysops': 'aws-sysops', 'soa-c02': 'aws-sysops',
    'aws-security': 'aws-security', 'scs-c02': 'aws-security',
    'aws-cloud-practitioner': 'aws-cloud-practitioner', 'clf-c02': 'aws-cloud-practitioner',
    'az-900': 'az-900', 'azure fundamentals': 'az-900',
    'az-104': 'az-104', 'az-204': 'az-204', 'az-305': 'az-305',
    'sc-900': 'sc-900', 'ai-900': 'ai-900',
    'gcp-pca': 'gcp-pca', 'gcp-ace': 'gcp-ace',
    pmp: 'pmp', capm: 'capm',
    cka: 'cka', ckad: 'ckad', terraform: 'terraform',
    psm: 'psm',
    'iso-27001-la': 'iso-27001-la', 'gdpr-practitioner': 'gdpr-practitioner', hipaa: 'hipaa',
    enem: 'enem', 'oab-primeira-fase': 'oab-primeira-fase', 'residencia-medica': 'residencia-medica',
};
